config/routes.rb
Poker::Application.routes.draw do
  get 'positions' => "handhistories#positions"
  get 'hands/winnings' => "hands#winnings"
  get 'winningpercent'=> "hands#percent_winning"
  get 'hands/losing' => "hands#losing"
  get "/frequency" => "hands#index"
  resources :handhistories

  resources :hands

  root :to => 'hands#homepage'

end

app/models/allin.rb
class Allin < ActiveRecord::Base
  # attr_accessible :title, :body
  set_table_name :allinsituations_hero
  belongs_to :handhistory, :class_name=> "Handhistory", :foreign_key => "playerhand_id"
end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
  set_primary_key "gametype_id"
  has_many :handhistories 
  
end

app/models/hand.rb
class Hand < ActiveRecord::Base
  set_table_name "holecards"
  set_primary_key "holecard_id"
  has_many :handhistories




  def self.bbwon(num_hands) 
    Hand.select{ |h| h.holecard_id < num_hands && h.holecard_id >0}.sort{ |a, b| a.bbwinings<=> b.bbwinings}.reverse.map { |h| h.bbwinings/100 }
  end
  def self.holecards(num_hands)
    Hand.select{|h| h.holecard_id <num_hands && h.holecard_id >0}.sort{ |a, b| a.winnings<=> b.winnings}.map { |h| h.holecardstring  }
  end


  def self.hand_winnings(hand_string)
    if hand_string.split.length >1
      hand1, hand2 = hand_string.split
      total_winnings = Hand.find_by_holecardstring(hand1).winnings + 
      Hand.find_by_holecardstring(hand2).winnings
    else
      total_winnings = Hand.find_by_holecardstring(hand_string).winnings
    end
    total_winnings
  end


  def self.position_winnings(id1, id2=nil)
    if id2
      id1_winnings = Hand.calc_position_winnings(id1)
      id2_winnings = Hand.calc_position_winnings(id2)
      Hand.add_array_elements(id1_winnings, id2_winnings)
    else
      Hand.calc_position_winnings(id1)
    end
  end

  def self.add_array_elements(array1, array2)
    array1.each_with_index.map { |a, index| a+array2[index] } 
  end

  def self.convert_to_winnings(array)
    array.map { |h| h.winnings.to_i/100 }
  end
  def self.calc_position_winnings(id)
      positions = Handhistory.select("positiontype_id, sum(netamountwon) as winnings").
      where("holecardvalue_id=? AND numberofplayers!=2", id ).group("positiontype_id").order("positiontype_id")
      position_winnings = convert_to_winnings(positions)
  end



end

app/models/handhistory.rb
class Handhistory < ActiveRecord::Base
  set_table_name "playerhandscashkeycolumns_hero"
  set_primary_key :pokerhand_id

  belongs_to :gametype
  belongs_to :hand, :class_name => "Hand", :foreign_key => "holecardvalue_id"


  has_one :allin, :class_name=> "Allin",  :foreign_key =>"playerhand_id"

  def self.winnings_over_days(type)
    winnings_per_day = Handhistory.select("day, sum(#{type}) as winnings").
    group("day").order("day").map{|h| h.winnings.to_i/100.0}
    accumulated_winnings_day = winnings_per_day.each_with_index.
    map{|n, index| winnings_per_day.take(index+1).sum}
  end


  def self.winnings_by_day(date)
    date_type = Handhistory.select("day, sum(bbwon) as winnings").group(date) 
    date_type.map{|y| y.winnings.to_i/100}
  end

  def self.percent_winning_hands_by_position
    winning_hands = {:sb=>0,:bb=>0,:utg => 0, :hj=> 0, :co=> 0, :btn=>0}
    hand_position_winnings = Handhistory.select("positiontype_id, sum(netamountwon) as winnings, holecardvalue_id").
    group("positiontype_id, holecardvalue_id").where("holecardvalue_id<170 AND numberofplayers!=2")
    hand_position_winnings.each do |hpw|
      case hpw.positiontype_id
        when 0
          winning_hands[:sb] +=1 if hpw.winnings.to_i >0
        when 1
          winning_hands[:bb] +=1 if hpw.winnings.to_i >0
        when 2            
          winning_hands[:utg] +=1 if hpw.winnings.to_i >0
        when 3
          winning_hands[:hj] +=1 if hpw.winnings.to_i >0
        when 4
          winning_hands[:co] +=1 if hpw.winnings.to_i >0
        when 5
          winning_hands[:btn] +=1 if hpw.winnings.to_i >0
      end
    end
      winning_hands.map{ |key, value| value/169.00*100}
  end




  def self.vpip_by_position
    positions ={:small_blind=>0, :big_blind =>0, :utg=>0, :utg1=>0, :co =>0, :btn =>0, :sbvpip=>0, :bbvpip=>0, :utgvpip=>0, :utg1vpip=>0, :covpip=>0, :btnvpip=>0}
    vpip = Handhistory.select("positiontype_id, numberofplayers, didvpip")
    vpip.each do |hand|
        case hand.positiontype_id
        when 0 
          positions[:small_blind] +=1 
          positions[:sbvpip] +=1 if hand.didvpip
        when 1
          positions[:big_blind] +=1
          positions[:bbvpip] +=1 if hand.didvpip
        when 2 
          positions[:utg] +=1
          positions[:utgvpip] +=1 if hand.didvpip
        when 3
          positions[:utg1] +=1
          positions[:utg1vpip] +=1 if hand.didvpip
        when 4
          positions[:co] +=1
          positions[:covpip] +=1 if hand.didvpip
        when 5
          positions[:btn] +=1
          positions[:btnvpip] +=1 if hand.didvpip
        end
      end
      positions
    end


  def self.winnings_by_position
    positions = Handhistory.select("positiontype_id, sum(netamountwon) as winnings").group("positiontype_id").where("numberofplayers!=2")
    positions.sort_by! { |pos| pos.positiontype_id}
    positions.map { |p| p.winnings.to_i/100 }
  end
  
  def self.group_hands(date_type)
    Handhistory.select("#{date_type}, sum(bbwon) as winnings").group("#{date_type}") 
  end

  def self.winnings_percent(group)
    times_winning = group.select{ |item| item.winnings.to_i > 0}.count
    times_losing = group.select { |item| item.winnings.to_i <0 }.count
 
    winning_percent = (times_winning*100)/((times_losing+times_winning))
  end

  def self.biggest_losers(num)
    Handhistory.select("holecardvalue_id, sum(netamountwon) as winnings").group("holecardvalue_id").
    sort{ |a, b| a.winnings.to_i <=> b.winnings.to_i}.
    take(num).map do |h| 
      # holecard = h.hand.holecard_id
      h.winnings.to_i/100
    end
  end

  def heads_up?
    true if self.numberofplayers ==2
  end
end

app/models/vsopponent.rb
class Vsopponent < ActiveRecord::Base
  # attr_accessible :title, :body
  set_table_name "playervsplayer_hero"
  set_primary_key "pokerhand_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/handhistories_controller.rb
class HandhistoriesController < ApplicationController
  # GET /handhistories
  # GET /handhistories.json
  def index
    # @handhistories = Handhistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handhistories }
    end
  end

  # GET /handhistories/1
  # GET /handhistories/1.json
  def show
    @handhistory = Handhistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handhistory }
    end
  end

end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  # GET /hands
  # GET /hands.json
  def homepage
    
  end
  def index
    @hands = Hand.all.select{ |h| h.holecard_id < 170}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hands }
    end
  end

  # GET /hands/1
  # GET /hands/1.json
  def show
    @hand = Hand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end
  def winnings
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end
  def percent_winning
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end
  def losing
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hand_helper.rb
module HandHelper
end

app/helpers/handhistories_helper.rb
module HandhistoriesHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/views/handhistories/_form.html.erb
<%= form_for(@handhistory) do |f| %>
  <% if @handhistory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handhistory.errors.count, "error") %> prohibited this handhistory from being saved:</h2>

      <ul>
      <% @handhistory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handhistories/edit.html.erb
<h1>Editing handhistory</h1>

<%= render 'form' %>

<%= link_to 'Show', @handhistory %> |
<%= link_to 'Back', handhistories_path %>

app/views/handhistories/index.html.erb
<div id="dollars" class = "span6"></div>


<div id='winnings_day' class = "span6"></div>


<div class="text">
<h1>Cash Game Winnings</h1>
<p class="main">Both graphs here show the same data in different form. The graph on the left shows my winnings in dollars and the graph on the right shows my winnings in big blinds.</p>

<p class="main">For those of you unfamiliar with a big blind, it's basically a way to normalize data. Throughout my poker career I've played stakes where the big blind is $2 up to games where the big blind is $50. If I want to look at these games equally I need to look at big blinds. If I win $20 in the former game and $500 in the latter, they both count as winning 10 big blinds.</p>

<p class="main">These graphs show that over the long run I win at poker. It may look like steady winnings but there are quite a few downswings in there including two that were ~$50k. The hardest thing to explain to people about poker is that you're <em>supposed</em> to lose sometimes. It's inevitable. But if you're a winner and keep playing you'll eventually start winning again.</p>

<strong><%= link_to "It's all about position", "/positions", :class=>"move-text"%></strong>

</div>

app/views/handhistories/new.html.erb
<h1>New handhistory</h1>

<%= render 'form' %>

<%= link_to 'Back', handhistories_path %>

app/views/handhistories/positions.html.erb
<div id = "winnings_by_position" class="graph span8"></div>
<div class="text">
<h3 >It's all about position</h3>


<p class="main">The importance of position is one of the most misunderstood things about poker to an amateur. The position your in matters just as much as the cards you're holding. Poker is a game of incomplete information and the more information you have, the better of a decision you can make. The way poker is structured is such that every position gets to make their decision after the positions before them. So position 1 gets to see what positions 0 does, position 2 gets to see what 0,1 do and 5 gets to see what everyone does before they have to play.</p>



<p class="main">This graph shows the amount of money I've won from every position. Positions 0 and 1 are the two <%= link_to "blinds", "http://en.wikipedia.org/wiki/Blind_(poker)"%> where it's impossible to win money. You're forced to put in money with 100% of hands and play from the worst positions at the table. The goal in these positions is the minimize your losses. Every position after the blinds you should be winning. Since each position is a little better than the one before you should win slightly more in every position and the most at position 5. </p>

<strong><%= link_to "Biggest winners", "/hands/winnings", :class=>"move-text"%></strong>

</div>

app/views/handhistories/show.html.erb
<p id="notice"><%= notice %></p>

app/views/hands/_form.html.erb
<%= form_for(@hand) do |f| %>
  <% if @hand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hand.errors.count, "error") %> prohibited this hand from being saved:</h2>

      <ul>
      <% @hand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hands/homepage.html.erb
<h1>About Me</h1>
<%=image_tag("poker.jpeg", :class=>"poker-pic graph")%>
<div class="text">

<p class="main">My name is James Vanneman. In October of 2012 I began attending the <%= link_to "Flatiron School", "http://www.flatironschool.com"%> and learning how to code. Before the Flatiron School, I made my living playing online poker. One of my projects over the course of the semester allowed me to combine two of my passions and create this website</p>

<p class="main">During my time as a professional, I played more than 2.1 million hands and logged all of them in a program called holdem manager. In addition to tracking my winnings and reviewing my sessions, holdem manager recorded all kinds of statistics about my play.</p>

<p class="main">The two forms of poker that professionals make their money from are "cash games" and "tournaments". The data that holdem manager recorded was from my cash games and that's what I'm using to create the graphs you'll see on this site. For this project, I wrapped my holdem manager database around Active Record and created a rails app from it. I used highcharts to create some visuals of the statistics I have and use them to show some interesting facts about poker</p>

<p class="main">I designed these statistics to be shown in a linear fashion so don't be tempted to skip around! I'll walk you through some poker best practices and give you an idea of some of the things that are important to being a winning poker player. If you have any questions of ideas of how I can improve the site feel free to email me</p>
<strong><%= link_to "Get Started", "/frequency", :class=>"move-text"%></strong>
</div>

app/views/hands/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Winning Frequency</h1>


<div id='holecards' class="graph" style = "width:760px"></div>
<div class="text">
<h3>Do you always win at poker?</h3>


<p class="main">This has to be one of the most frequently asked questions by people. The answer is absolutely not. This graph shows the percent of the time I win by hand, day, month and year. As you can see I don't win that many hands but over the course of a day I play a lot of hands and am much more likely to win on any given day than on any given hand. In a month I'm much more likely to win than on any specific day or hand and I've never had a losing year.</p>

<p class="main">The lesson you can take from this is that over the long run it's much more likely that I end up a winner. Poker is a game based off statistics. On any given hand or day I might lose but if I play for long enough I usually end up winning.</p>

<strong><%= link_to "Winnings over time", "/handhistories", :class=>"move-text"%></strong>

</div>

app/views/hands/losing.html.erb
<h1> Losing</h1>
<%#=javascript_include_tag "hands/losing/losing.js.erb" %>
<div id = "losing" height:400px class="span8 graph"></div>
<div class="text">
<h3>Top losers</h3>

<p class="main">These are the hands I've lost the most with. If you click on the columns you can see their losing distribution by position. These hands are generally way too weak to ever play. Ideally I should only be losing money with these hands from the blinds(because I was forced to put money in and then I folded), but you can tell I've lost a little bit from other positions as well. I can't really justify ever playing these hands from some of the positions I've lost money from but nobody's perfect, we all do silly things sometimes :).</p>

<strong><%= link_to "Winning Percent", "/winningpercent", :class=>"move-text"%></strong>

</div>

app/views/hands/percent_winning.html.erb
<div id='percent' class = "span8 graph" style = "height: 400px"></div>
<div class="text">
<h3>Winning Hands Percent</h3>

<p class="main">So you're probably still wondering why I'm winning more money in every position closer to 5 but with my best hands I'm winning the most from positions 0 and 1. It's not that every hand is worth more in each position closer to 5, clearly my best hands are worth more in positions 0 and 1. The reason is the <em>a higher percentage of hands win money</em> in every position closer to 5. This means that I win money with the fewest percent of hands in positions 0 and 1 and the highest percent of hands on position 5. So the cards in your hand matter, but certain cards may be winning in some positions and losing in others. Position is incredibly important</p>

<em>Note</em>
<p>Positions 2 and 3 are definitely off here. I know the real numbers should be more around 20%. I think the reason they're skewed here has to do with some special tables that full tilt used to have. If you played on there and remember the "reserved" tables that players could buy I'm pretty sure those threw off the numbers a bit.</p>

</div>

app/views/hands/winnings.html.erb
<div id="tophands" class = "span8 graph"></div>




<div class="text">
<h3>Top winners</h3>


<p class="main">These are the hands that I've won the most money with. The specific hands probably aren't that much of a surprise to you, however there is some interesting data in here.</p>

<p class="main">Based on my explanation of the last page, what positions would you expect me to win the most money from with each of these hands?</p>

<p class="main">Ok now click on one of the columns and see if you're right!</p>


<div class="dd-paragraph"><p class="main">Now that's interesting! I just told you that position 5 is best position to be in and you saw from my earlier graph that it's where I win the most money. However with my best hands I'm clearly winning more money from the worst positions at the table. I'll get into exactly how this works at the end, for now head to the next graph and see my <strong><%=link_to "Biggest losing hands", "/hands/losing", :class=>"move-text"%></strong> </p></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Poker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="poker">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%=link_to "Poker on Rails", root_url, :class=> "brand"%>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Winning Frequency", :controller=>"hands", :action=>"index", :class=>"nav"%></li>
              <li><%= link_to "Cash Game Winnings", "/handhistories", :class=>"nav"%></li>
              <li><%= link_to "Positions", "/positions", :class=>"nav"  %></li>
              <li><%= link_to "Biggest Winners", "/hands/winnings", :class=>"nav"  %></li>
              <li><%= link_to "Biggest Losers", "/hands/losing", :class=>"nav"  %></li>
              <li><%= link_to "Percent by position", "/winningpercent", :class=>"nav"%></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div>
             <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; jvans2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <%= javascript_include_tag "application" %>

  </body>
</html>